[Scalars](#scalars)<br>
[vectors](#vectors)<br>
[Length, Dimensionality, and Shape](#length_dimensionalit_shape)<br>
[Matrices](#matrices)<br>
[Tensors](#tensors)<br>
[Basics Properties of Tensor Artithmetic](#tensor_arithmetic)<br>
[Reduction](#reduction)

---
### Scalars
<a id = 'scalars'></a>

In [63]:
import tensorflow as tf

x = tf.constant([3.0])
y = tf.constant([2.0])

x + y, x - y, x * y, x / y, x ** y

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([5.], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([6.], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.5], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([9.], dtype=float32)>)

---
### Vectors
<a id= 'vectors'></a>

In [64]:
x = tf.range(4)
x[3]

<tf.Tensor: shape=(), dtype=int32, numpy=3>

---
### Length, Dimensionality, and Shape
<a id='tensor_format_conversion'></a>

In [65]:
x.shape

TensorShape([4])

---
### Matrices
<a id='matrices'></a>

In [66]:
A = tf.reshape(tf.range(20), (5,4))
A

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])>

In [67]:
tf.transpose(A)

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])>

Symmetric matrix

In [68]:
B = tf.constant([[1, 2, 3] , [2, 0, 4] , [3, 4, 5]])
B

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 0, 4],
       [3, 4, 5]])>

In [69]:
B == tf.transpose(B)

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])>

---
### Tensors
<a id='tensors'></a>

In [70]:
X = tf.reshape(tf.range(24) , (2, 3, 4))
X

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])>

---
### Basic Properties of Tensor Arithmetic
<a id='tensor_arithmetic'></a>

In [71]:
A = tf.reshape(tf.range(20, dtype = tf.float32), (5, 4))
B = A
A , A + B

(<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]], dtype=float32)>,
 <tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]], dtype=float32)>)

In [72]:
A * B

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[  0.,   1.,   4.,   9.],
       [ 16.,  25.,  36.,  49.],
       [ 64.,  81., 100., 121.],
       [144., 169., 196., 225.],
       [256., 289., 324., 361.]], dtype=float32)>

In [73]:
a = 2 
X = tf.reshape(tf.range(24), (2,3,4))
a + X , (X * 2).shape

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],
 
        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])>,
 TensorShape([2, 3, 4]))

---
### reduction
<a id = 'reduction'></a>

In [78]:
x = tf.range(4, dtype = tf.float32)
x , tf.reduce_sum(x)

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 1., 2., 3.], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=6.0>)

In [79]:
A.shape, tf.reduce_sum(A)

(TensorShape([5, 4]), <tf.Tensor: shape=(), dtype=float32, numpy=190.0>)