[Scalars](#scalars)<br>
[vectors](#vectors)<br>
[Length, Dimensionality, and Shape](#length_dimensionalit_shape)<br>
[Matrices](#matrices)<br>
[Tensors](#tensors)<br>
[Basics Properties of Tensor Artithmetic](#tensor_arithmetic)<br>
[Reduction](#reduction)<br>
[Non Reduction Sum](#non_reduction_sum)<br>
[Dot products](#dot_products)<br>
[Matrix Vector Products](#matrix_vector_products)<br>
[Matrix Matrix Multiplication](#matrix_matrix_multiplication)

---
### Scalars
<a id = 'scalars'></a>

In [75]:
import tensorflow as tf

x = tf.constant([3.0])
y = tf.constant([2.0])

x + y, x - y, x * y, x / y, x ** y

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([5.], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([6.], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.5], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([9.], dtype=float32)>)

---
### Vectors
<a id= 'vectors'></a>

In [76]:
x = tf.range(4)
x[3]

<tf.Tensor: shape=(), dtype=int32, numpy=3>

---
### Length, Dimensionality, and Shape
<a id='tensor_format_conversion'></a>

In [77]:
x.shape

TensorShape([4])

---
### Matrices
<a id='matrices'></a>

In [78]:
A = tf.reshape(tf.range(20), (5,4))
A

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])>

In [79]:
tf.transpose(A)

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])>

Symmetric matrix

In [80]:
B = tf.constant([[1, 2, 3] , [2, 0, 4] , [3, 4, 5]])
B

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 0, 4],
       [3, 4, 5]])>

In [81]:
B == tf.transpose(B)

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])>

---
### Tensors
<a id='tensors'></a>

In [82]:
X = tf.reshape(tf.range(24) , (2, 3, 4))
X

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])>

---
### Basic Properties of Tensor Arithmetic
<a id='tensor_arithmetic'></a>

In [83]:
A = tf.reshape(tf.range(20, dtype = tf.float32), (5, 4))
B = A
A , A + B

(<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]], dtype=float32)>,
 <tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]], dtype=float32)>)

In [84]:
A * B

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[  0.,   1.,   4.,   9.],
       [ 16.,  25.,  36.,  49.],
       [ 64.,  81., 100., 121.],
       [144., 169., 196., 225.],
       [256., 289., 324., 361.]], dtype=float32)>

In [85]:
a = 2 
X = tf.reshape(tf.range(24), (2,3,4))
a + X , (X * 2).shape

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],
 
        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])>,
 TensorShape([2, 3, 4]))

---
### reduction
<a id = 'reduction'></a>

In [86]:
x = tf.range(4, dtype = tf.float32)
x , tf.reduce_sum(x)

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 1., 2., 3.], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=6.0>)

In [87]:
A.shape, tf.reduce_sum(A)

(TensorShape([5, 4]), <tf.Tensor: shape=(), dtype=float32, numpy=190.0>)

In [88]:
A_sum_axis1 = tf.reduce_sum(A , axis = 1) #column dimension
A_sum_axis0 = tf.reduce_sum(A, axis = 0) #row dimension
A_sum_axis1.shape ,A_sum_axis1, A_sum_axis0.shape, A_sum_axis0

(TensorShape([5]),
 <tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 6., 22., 38., 54., 70.], dtype=float32)>,
 TensorShape([4]),
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([40., 45., 50., 55.], dtype=float32)>)

In [89]:
tf.reduce_mean(A , axis = 0) , tf.reduce_sum(A , axis =  0) / A.shape[0]

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 8.,  9., 10., 11.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 8.,  9., 10., 11.], dtype=float32)>)

---
### Non Reduction Sum
<a id = 'non_reduction_sum'></a>

In [90]:
sum_A = tf.reduce_sum(A, axis = 1 , keepdims=True)
sum_A 

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[ 6.],
       [22.],
       [38.],
       [54.],
       [70.]], dtype=float32)>

In [91]:
A / sum_A #broadcasting a reduced sum which has two dimensions

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0.        , 0.16666667, 0.33333334, 0.5       ],
       [0.18181819, 0.22727273, 0.27272728, 0.3181818 ],
       [0.21052632, 0.23684211, 0.2631579 , 0.28947368],
       [0.22222222, 0.24074075, 0.25925925, 0.2777778 ],
       [0.22857143, 0.24285714, 0.25714287, 0.27142859]], dtype=float32)>

In [92]:
tf.cumsum(A, axis = 0)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  6.,  8., 10.],
       [12., 15., 18., 21.],
       [24., 28., 32., 36.],
       [40., 45., 50., 55.]], dtype=float32)>

---
### Dot products
<a id = 'dot_products'></a>

In [93]:
y = tf.ones(4, dtype = tf.float32)
x, y, tf.tensordot(x , y, axes = 1)

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 1., 2., 3.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=6.0>)

dot product expressed elementwise multiplication and then the reduced sum

In [94]:
tf.reduce_sum(x * y)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

---
### Matrix Vector products
<a id = 'matrix_vector_products'></a>

In [95]:
A.shape, x.shape, tf.linalg.matvec(A, x) 

(TensorShape([5, 4]),
 TensorShape([4]),
 <tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 14.,  38.,  62.,  86., 110.], dtype=float32)>)

---
### Matrix Matrix multiplication
<a id = 'matrix_matrix_multiplication'></a>

In [97]:
B = tf.ones((4,3) , tf.float32)
tf.matmul(A, B)

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[ 6.,  6.,  6.],
       [22., 22., 22.],
       [38., 38., 38.],
       [54., 54., 54.],
       [70., 70., 70.]], dtype=float32)>