[data manipulation](#datamanipulation)<br>
[operations](#operation)

***

### data manipulation
<a id='datamanipulation'></a>

In [577]:
import tensorflow as tf

In [578]:
x = tf.range(12)
x

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])>

In [579]:
x.shape

TensorShape([12])

In [580]:
tf.size(x)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [581]:
X = tf.reshape(x, (3,4))
X

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

In [582]:
tf.size(X)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

##### reshape with specifying only one dimension

In [583]:
Y = tf.reshape(x,(-1, 4))
Y

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

In [584]:
tf.zeros((2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [585]:
tf.ones((2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [586]:
tf.random.normal(shape= [3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.21091537,  1.475682  , -1.4709243 ,  1.5836586 ],
       [-0.12977886,  0.01200941,  1.5412399 , -1.0768238 ],
       [ 0.82856   , -1.3538394 ,  1.222822  , -0.12055118]],
      dtype=float32)>

In [587]:
tf.constant([[2 , 1, 4,3 ] , [1, 2, 3, 4], [4, 3, 2, 1]])

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[2, 1, 4, 3],
       [1, 2, 3, 4],
       [4, 3, 2, 1]])>

***

### operations
<a id='operation'></a>