In [1]:
import tensorflow as tf
import tensorflow.keras as keras
import numpy as np


In [2]:
class ReducedDense(keras.Model):
    def __init__(self, units, k):
        super().__init__()
        self.units = units
        self.no_of_weights = k
    
    def build(self, input):
            self.weight = tf.Variable(np.random.uniform(0, 1, size=(self.no_of_weights, self.units , input[-1])), dtype=tf.float32)
            print(self.weight.shape)
            
    def call(self, X ):
        out =  tf.matmul(tf.transpose(X), X)
        y = self.weight[2] 
        return [tf.matmul(self.weight[i] , out ) for i in range(self.no_of_weights)]
        
        
    

In [3]:
dense = ReducedDense(3, 4 )
dense(tf.random.uniform((2, 5)))

(4, 3, 5)


[<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
 array([[1.4702377 , 0.6974827 , 2.2187548 , 2.1723022 , 3.1104894 ],
        [1.1871557 , 0.5868316 , 1.3668022 , 1.1532879 , 2.172224  ],
        [0.60646194, 0.27467352, 1.1493514 , 1.2272085 , 1.47012   ]],
       dtype=float32)>,
 <tf.Tensor: shape=(3, 5), dtype=float32, numpy=
 array([[1.0012593 , 0.48000753, 1.4210312 , 1.3521097 , 2.0464072 ],
        [0.9977441 , 0.47940075, 1.3966683 , 1.3199608 , 2.0237436 ],
        [0.43132132, 0.18241605, 1.0497912 , 1.201449  , 1.2312155 ]],
       dtype=float32)>,
 <tf.Tensor: shape=(3, 5), dtype=float32, numpy=
 array([[1.0662556 , 0.512625  , 1.4870845 , 1.4028356 , 2.1583219 ],
        [0.94007117, 0.4502172 , 1.3423915 , 1.2810804 , 1.9279015 ],
        [0.75972104, 0.35410342, 1.2598488 , 1.2828122 , 1.6978536 ]],
       dtype=float32)>,
 <tf.Tensor: shape=(3, 5), dtype=float32, numpy=
 array([[0.773331  , 0.3493951 , 1.480963  , 1.5866098 , 1.8869028 ],
        [1.251149  , 0.584307