In [1]:
import tensorflow as tf
import tensorflow.keras as keras
class CenteredLayer(keras.Model):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
    
    def call(self, inputs):
        return inputs - tf.reduce_mean(inputs)

In [2]:
layer = CenteredLayer()
layer(tf.constant([1, 2, 3, 4, 5]))

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([-2, -1,  0,  1,  2])>

In [3]:
net = keras.Sequential([keras.layers.Dense(128), CenteredLayer() ])

In [4]:
Y = net(tf.random.uniform((4, 8)))
tf.reduce_mean(Y)

<tf.Tensor: shape=(), dtype=float32, numpy=6.9849193e-10>

In [7]:
class MyDense(keras.Model):
    def __init__(self, units):
        super().__init__()
        self.units = units
    
    def build(self, input_shape):
        self.weight = self.add_weight(name = 'weight', shape = [input_shape[-1], self.units], initializer = tf.random_normal_initializer())
        self.bias = self.add_weight(name = 'bias', shape = [self.units], initializer = tf.random_normal_initializer() )
    
    def call(self, X):
        linear = tf.matmul(X, self.weight) + self.bias
        return tf.nn.relu(linear)
        
    

In [8]:
dense = MyDense(3)
dense(tf.random.uniform((2, 5)))
dense.get_weights()

[array([[-0.00656898, -0.00820548, -0.00808255],
        [-0.04272729,  0.01418535, -0.00579469],
        [-0.0030478 ,  0.04730418, -0.09074584],
        [ 0.00936914,  0.04563896, -0.03677152],
        [-0.00550771, -0.07360804,  0.01917743]], dtype=float32),
 array([ 0.02544244,  0.00242849, -0.06398969], dtype=float32)]

In [9]:
net = keras.models.Sequential([MyDense(8), MyDense(1)])
net(tf.random.uniform((2, 64)))

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.02375554],
       [0.01387836]], dtype=float32)>