In [14]:
import tensorflow as tf
import numpy as np
import tensorflow.keras as keras

In [15]:
x = tf.range(4)
np.save('x-file.npy', x)

In [16]:
x2 = np.load('x-file.npy', allow_pickle=True)
x2

array([0, 1, 2, 3])

In [17]:
y = tf.zeros(4)
np.save('xy-files.npy', [x, y])
x2, y2 = np.load('xy-files.npy', allow_pickle=True)
(x2, y2)

(array([0., 1., 2., 3.]), array([0., 0., 0., 0.]))

In [18]:
mydict = {'x':x, 'y':y}
np.save('mydict.npy', mydict)
mydict2 = np.load('mydict.npy', allow_pickle= True)
mydict2

array({'x': <tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3])>, 'y': <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>},
      dtype=object)

In [23]:
class MLP(keras.Model):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.flatten = keras.layers.Flatten()
        self.hidden = keras.layers.Dense(256, activation=tf.nn.relu)
        self.out = keras.layers.Dense(10)
    
    def call(self, X):
        return self.out(self.hidden(self.flatten(X)))
    
input = np.random.uniform((2, 20))
net = MLP()
Y = net(input)


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



In [24]:
net.save_weights('mlp.params')

In [25]:
clone = MLP()
clone.load_weights('mlp.params')

In [26]:
Y_clone = clone(input)
Y_clone == Y


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



<tf.Tensor: shape=(2, 10), dtype=bool, numpy=
array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])>