In [1]:
import tensorflow as tf
import tensorflow.keras as keras

net = keras.models.Sequential([
    keras.layers.Flatten(),
    keras.layers.Dense(4, activation = tf.nn.relu),
    keras.layers.Dense(1)
])

X = tf.random.uniform((2, 4))
net(X)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.6981816 ],
       [-0.54036057]], dtype=float32)>

In [2]:
net.layers[2].weights, net.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (2, 4)                    0         
_________________________________________________________________
dense (Dense)                (2, 4)                    20        
_________________________________________________________________
dense_1 (Dense)              (2, 1)                    5         
Total params: 25
Trainable params: 25
Non-trainable params: 0
_________________________________________________________________


([<tf.Variable 'dense_1/kernel:0' shape=(4, 1) dtype=float32, numpy=
  array([[-0.8833629 ],
         [-1.0624901 ],
         [-0.21926719],
         [-0.787276  ]], dtype=float32)>,
  <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>],
 None)

In [3]:
print(net.layers[2].weights[1])
print(tf.convert_to_tensor(net.layers[2].weights[1]))

<tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>
tf.Tensor([0.], shape=(1,), dtype=float32)


In [4]:
print(net.get_weights())

[array([[-0.37501797,  0.84488636,  0.7113971 , -0.685379  ],
       [-0.25694746,  0.17305475, -0.5971384 , -0.44869542],
       [-0.77803624,  0.30461687, -0.02566749, -0.3128227 ],
       [ 0.5476065 , -0.7738194 ,  0.4352041 ,  0.06677824]],
      dtype=float32), array([0., 0., 0., 0.], dtype=float32), array([[-0.8833629 ],
       [-1.0624901 ],
       [-0.21926719],
       [-0.787276  ]], dtype=float32), array([0.], dtype=float32)]


In [5]:
print(len(net.get_weights())), print(net.get_weights()[1])

4
[0. 0. 0. 0.]


(None, None)

In [6]:
def block1(name):
    return keras.models.Sequential([
        keras.layers.Flatten(),
        keras.layers.Dense(4, activation= tf.nn.relu),
    
    ], name = name)
    
def block2():
    net = keras.models.Sequential()
    for i in range(4):
        net.add(block1(name = f'block-{i}'))
    return net

rgnet = keras.models.Sequential()
rgnet.add(block2())
rgnet.add(keras.layers.Dense(1))
rgnet(X)



<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.5793845],
       [0.5411532]], dtype=float32)>

In [7]:
print(rgnet.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
sequential_2 (Sequential)    (2, 4)                    80        
_________________________________________________________________
dense_6 (Dense)              (2, 1)                    5         
Total params: 85
Trainable params: 85
Non-trainable params: 0
_________________________________________________________________
None


In [8]:
rgnet.layers[0].layers[1].layers[1].get_weights()

[array([[-0.78924793, -0.21745658,  0.04612499,  0.6686247 ],
        [ 0.7360721 ,  0.52344304, -0.20845848,  0.5855027 ],
        [-0.79909354, -0.6905996 ,  0.3858052 ,  0.7430673 ],
        [ 0.5731124 , -0.5192701 ,  0.6133968 , -0.00160617]],
       dtype=float32),
 array([0., 0., 0., 0.], dtype=float32)]

In [9]:
net = keras.models.Sequential([
    keras.layers.Flatten(),
    keras.layers.Dense(4, activation=tf.nn.relu, kernel_initializer=tf.random_normal_initializer(mean=0, stddev=.01),
                       bias_initializer = tf.zeros_initializer()),
    keras.layers.Dense(1)
])

net(X)
net.weights[0], net.weights[1], net.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_5 (Flatten)          (2, 4)                    0         
_________________________________________________________________
dense_7 (Dense)              (2, 4)                    20        
_________________________________________________________________
dense_8 (Dense)              (2, 1)                    5         
Total params: 25
Trainable params: 25
Non-trainable params: 0
_________________________________________________________________


(<tf.Variable 'dense_7/kernel:0' shape=(4, 4) dtype=float32, numpy=
 array([[ 0.00683765,  0.00098835, -0.00499818,  0.02634917],
        [ 0.00810222, -0.01525083, -0.01385352, -0.00394089],
        [ 0.00030069,  0.00889236,  0.02368973,  0.0168944 ],
        [-0.00046644,  0.00849263, -0.01445713,  0.00022631]],
       dtype=float32)>,
 <tf.Variable 'dense_7/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>,
 None)

In [11]:
net = keras.models.Sequential([
    keras.layers.Flatten(),
    keras.layers.Dense(4, activation=tf.nn.relu, kernel_initializer=tf.constant_initializer(1),
                       bias_initializer = tf.zeros_initializer()),
    keras.layers.Dense(1)
])

net(X)
net.weights[0], net.weights[1]

(<tf.Variable 'dense_11/kernel:0' shape=(4, 4) dtype=float32, numpy=
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32)>,
 <tf.Variable 'dense_11/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'dense_12/kernel:0' shape=(4, 1) dtype=float32, numpy=
 array([[-0.17762005],
        [-0.52224344],
        [-0.27549207],
        [ 0.1544205 ]], dtype=float32)>)

In [17]:
class MyInit(tf.keras.initializers.Initializer):
    def __call__(self, shape, dtype = None):
        data = tf.random.uniform(shape, -10, 10, dtype = dtype)
        factor = (tf.abs(data) >= 5)
        factor = tf.cast(factor, tf.float32)
        return data * factor
    
net = keras.models.Sequential([
    keras.layers.Flatten(),
    keras.layers.Dense(4, activation=tf.nn.relu, kernel_initializer=MyInit()), 
    keras.layers.Dense(1)
])

net(X)
print(net.layers[1].weights[0])
        

<tf.Variable 'dense_13/kernel:0' shape=(4, 4) dtype=float32, numpy=
array([[ 7.226507 , -5.7879996,  0.       ,  6.486471 ],
       [-5.8793545, -7.746544 ,  0.       ,  6.2583504],
       [-7.0257425,  0.       , -8.705349 ,  6.4796677],
       [ 6.9662247,  8.512766 ,  0.       ,  0.       ]], dtype=float32)>
